ToDoListWithType/Models/Category.cs
using System.Collections.Generic; 
namespace ToDoListWithType.Models
{
    public class Category
    {
        public string name {get;set;}
        public int CategoryId {get;set;}
        public virtual ICollection<Item> Items {get;set;}
        public Category()
        {
            this.Items = new HashSet<Item>();
        }
        
    }
}

ToDoListWithType/Models/Item.cs
using System.Collections.Generic; 
namespace ToDoListWithType.Models
{
    public class Item
    {
        public string description {get;set;}
        public int CategoryId {get;set;}
        public int ItemId {get;set;}
        public virtual Category Category {get;set;}

       

    }
}

ToDoListWithType/Models/ToDoListContext.cs
using Microsoft.EntityFrameworkCore;

namespace ToDoListWithType.Models
{
    public class ToDoListWithTypeContext:DbContext
    {
        public virtual DbSet<Category> Categories {get;set;}
        public DbSet<Item> Items {get;set;}
        public ToDoListWithTypeContext(DbContextOptions options):base(options){}

    } 
}

ToDoListWithType/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoListWithType.Models;
using System.Collections.Generic;
using System.Linq;

namespace ToDoListWithType.Controllers
{
  public class CategoriesController : Controller
  {

   private readonly ToDoListWithTypeContext _dataBase;
   public CategoriesController(ToDoListWithTypeContext dataBase)
   {
     _dataBase = dataBase;
   }
    [HttpGet]
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Category new_category)
    {
        _dataBase.Categories.Add(new_category);
        _dataBase.SaveChanges();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public ActionResult Index()
    {
      List<Category> lsitOfCategories = _dataBase.Categories.ToList();
      return View(lsitOfCategories);
    }
    [HttpGet]
    public ActionResult Details(int id)
    {
      Category CategoryInDetail = _dataBase.Categories.FirstOrDefault(categories => categories.CategoryId==id);
      CategoryInDetail.Items = _dataBase.Items.Where(rowItems => rowItems.CategoryId==id).ToList();
      return View(CategoryInDetail);
    }
    [HttpGet]
    public ActionResult Update(int CategoryID)
    {
      Category foundCatgeory = _dataBase.Categories.FirstOrDefault(categories => categories.CategoryId==CategoryID);

      return View(foundCatgeory);
    }
    [HttpPost]
    public ActionResult Update(Category new_category)
    {
      _dataBase.Entry(new_category).State = EntityState.Modified;
      _dataBase.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpGet]
    public ActionResult Remove(int idForDeleting)
    {
      Category categoryForDeleting = _dataBase.Categories.FirstOrDefault(rows => rows.CategoryId==idForDeleting);
      return View(categoryForDeleting);
    }
    [HttpPost,ActionName("Remove")]
    public ActionResult RemoveConfirmed(int idForDeleting)
    {
      Category removingCategory = _dataBase.Categories.FirstOrDefault(RelationalReferenceOwnershipBuilderExtensions => RelationalReferenceOwnershipBuilderExtensions.CategoryId==idForDeleting);
      _dataBase.Remove(removingCategory);
      _dataBase.SaveChanges();
      return RedirectToAction("Index");
    }
    
    

    


  


  

  }
}

ToDoListWithType/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
 using ToDoListWithType.Models;

namespace  ToDoListWithType.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

ToDoListWithType/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoListWithType.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ToDoListWithType.Controllers
{
    public class ItemsController : Controller
    {
     private readonly ToDoListWithTypeContext _dataBase;
     public ItemsController(ToDoListWithTypeContext dataBase)
     {
         _dataBase = dataBase;
     }
     public ActionResult Index()
     {
         List<Item> items = _dataBase.Items.Include(itemRows => itemRows.Category).ToList();
         return View(items);
     }
     [HttpGet]
     public ActionResult Create()
     {
         ViewBag.CategoryId = new SelectList(_dataBase.Categories,"CategoryId","name");
         
         return View();
     }
     [HttpPost]
     public ActionResult Create(Item new_item)
     {
         _dataBase.Add(new_item);
         _dataBase.SaveChanges();
         return RedirectToAction("Index");
     }
     [HttpGet]
     public ActionResult Details(int idForItems)
     {
            Item itemDetail = _dataBase.Items.FirstOrDefault(itemRows => itemRows.ItemId==idForItems);
            return View(itemDetail);

     }
     [HttpGet]
     public ActionResult Update(int updateID)
     {
         Item foundItem = _dataBase.Items.FirstOrDefault(rowItems => rowItems.ItemId==updateID);
         ViewBag.CategoryId = new SelectList(_dataBase.Categories,"CategoryId","name");
         return View(foundItem);
     }
     [HttpPost]
     public ActionResult Update(Item items)
     {
         _dataBase.Entry(items).State = EntityState.Modified;
         _dataBase.SaveChanges();
         return RedirectToAction("Index");
     }
     [HttpGet]
     public ActionResult Delete(int deleteID)
     {
         Item foundItem = _dataBase.Items.FirstOrDefault(rowItems => rowItems.ItemId==deleteID);
         return View(foundItem);
     }
     [HttpPost,ActionName("Delete")]
     public ActionResult DeleteItem(int deleteID)
     {
         Item deletingItem = _dataBase.Items.FirstOrDefault(rowItems=>rowItems.ItemId==deleteID);
         _dataBase.Remove(deletingItem);
         _dataBase.SaveChanges();
         return RedirectToAction("Index");

     }
    
        

       
    }
}

ToDoListWithType/Views/Categories/Create.cshtml
@{
  Layout = "_Layout";
}
@model ToDoListWithType.Models.Category

<h4>Add a new Category</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.name)
    @Html.TextBoxFor(model => model.name)
    <input type="submit" value="Add new category" />
}
<p>@Html.ActionLink("Show all categories", "Index")</p>
<p>@Html.ActionLink("Return Home Page", "Index","Home")</p>

ToDoListWithType/Views/Categories/Details.cshtml
@{
  Layout = "_Layout";
}

@using ToDoListWithType.Models;
@model ToDoListWithType.Models.Category;

<hr/>
<h3>@Html.DisplayNameFor(model => model.name): @Html.DisplayFor(model => model.name)</h3>

<ul>
    @if(@Model.Items.Count == 0)
    {
        <p>no items found </p>
    }
    @foreach(Item item in @Model.Items)
    {
        <li>Description: @item.description</li>
    }
</ul>
<p>@Html.ActionLink("Add new  Item","Create","Items")</p>
<p>@Html.ActionLink("Update category","Update",new {CategoryID=Model.CategoryId})</p>
<p>@Html.ActionLink("Delete category","Remove",new {idForDeleting=Model.CategoryId})</p>

<p>@Html.ActionLink("Back to list of categories","Index")</p>

ToDoListWithType/Views/Categories/Index.cshtml
@{
  Layout = "_Layout";
}
@using ToDoListWithType.Models;
@model List<ToDoListWithType.Models.Category>;
<h1>Categories</h1>
@if(@Model.Count==0)
{
    <h4>There is no categories in our list.</h4>
}
<ul> 
  @foreach(Category category in Model)
  {
      <li>@Html.ActionLink($"{category.name}",  "Details", new { id = category.CategoryId })</li>
  }
</ul>
<hr/>
<p>@Html.ActionLink("Add new category", "Create")</p>
<p>@Html.ActionLink("Return Home Page","Index","Home")</p>

ToDoListWithType/Views/Categories/Remove.cshtml
@{
  Layout = "_Layout";
}

@model ToDoListWithType.Models.Category

<h2>Are you sure you want to delete this?</h2>
<h3>@Html.DisplayNameFor(model => model.name): @Html.DisplayFor(model => model.name)</h3>
@using (Html.BeginForm())
{
    
    <input type="submit" value="Remove" />
}
@Html.ActionLink("Back to List", "Index")

ToDoListWithType/Views/Categories/Update.cshtml
@{
  Layout = "_Layout";
}

@model ToDoListWithType.Models.Category;
<h4>Update this Category: </h4><br>
<h3>@Html.DisplayNameFor(model => model.name): @Html.DisplayFor(model => model.name)</h3>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model=>model.CategoryId)
    @Html.LabelFor(model=>model.name)
    @Html.TextBoxFor(model=> model.name)
    <input type ="submit" value="Update" />
}

ToDoListWithType/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<center>
 <h1>Welcome Category Project.</h1>
 <br>
 <br>
 <br>
 <hr/>
 <br>
 <p></p>
 <p>@Html.ActionLink("See all categories", "Index", "Categories")</p> 
 <p>@Html.ActionLink("Add a new category", "Create", "Categories")</p> 
 <p>@Html.ActionLink("Home","Index","Home")</p>
</center>
   

  

ToDoListWithType/Views/Items/Create.cshtml
@{
  Layout = "_Layout";
}
@model ToDoListWithType.Models.Item

<h4>Add a new Item</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.description)
    @Html.TextBoxFor(model => model.description)

    @Html.LabelFor(model=> model.Category)
    @Html.DropDownList("CategoryId")
    <input type="submit" value="Add new item" />
}
<p>@Html.ActionLink("Show all items", "Index")</p>
<p>@Html.ActionLink("Show all categories","Index","Categories")</p>
<p>@Html.ActionLink("Return Home Page", "Index","Home")</p>

ToDoListWithType/Views/Items/Delete.cshtml
@{
  Layout = "_Layout";
}

@model ToDoListWithType.Models.Item

<h2>Are you sure you want to delete this?</h2>
<h3>@Html.DisplayNameFor(model => model.description): @Html.DisplayFor(model => model.description)</h3>
@using (Html.BeginForm())
{
    
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

ToDoListWithType/Views/Items/Details.cshtml
@{
  Layout = "_Layout";
}

@model ToDoListWithType.Models.Item

<h2>Item Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.description): @Html.DisplayFor(model => model.description)</h3>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Update Item", "Update", new { updateID = Model.ItemId })</p>
<p>@Html.ActionLink("Delete Item", "Delete", new { deleteID = Model.ItemId })</p>

ToDoListWithType/Views/Items/Index.cshtml
@{
  Layout = "_Layout";
}

@using ToDoListWithType.Models;
@model List<ToDoListWithType.Models.Item>;

<h1>Items</h1>

@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
} 

@foreach (Item item in Model)
{
  <li>@Html.ActionLink($"{item.description}", "Details", new { idForItems = item.ItemId }) | @item.Category.name</li>
}

<p>@Html.ActionLink("Add new item", "Create")</p>
<p>@Html.ActionLink("Back to List of Categories", "Index","Categories")</p>
<p>@Html.ActionLink("Back to Home Page", "Index","Home")</p>

ToDoListWithType/Views/Items/Update.cshtml
@{
  Layout = "_Layout";
}

@model ToDoListWithType.Models.Item;
<h4>Update this Item: </h4><br>
<h3>@Html.DisplayNameFor(model => model.description): @Html.DisplayFor(model => model.description)</h3>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model=>model.ItemId)
    @Html.LabelFor(model=>model.description)
    @Html.TextBoxFor(model=> model.description)

    @Html.LabelFor(model=>model.Category)
    @Html.DropDownList("CategoryId")
    <input type ="submit" value="Update" />
}

ToDoListWithType/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>To Do List With Category</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>

    @RenderBody()
  </body>
</html>